### ISSUE TITLE
Make core file available as Composer package

### ISSUE THREAD

**Issue by GaryJones** [samikeijonen/bemit#1]
Could you make the main filters be available as a standalone Composer package, so that they could be consumed by other themes, more than just copy and paste?

**Comment by samikeijonen** [comment]
@GaryJones I can do that. Would that be a WordPress plugin or just code in `functions-filters.php`?

**Comment by GaryJones** [comment]
Just the code - a (Composer) _package_, rather than a WP _plugin_.

**Comment by samikeijonen** [comment]
There is now [own repo for filters](https://github.com/samikeijonen/bem-nav-filters).
